import os
import discord, asyncio
from dotenv import load_dotenv
from discord import FFmpegPCMAudio
from discord.ext import commands
from discord.utils import get
from datetime import datetime
from collections import defaultdict

load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')

intents = discord.Intents.all()
intents.members = True  # Subscribe to the privileged members intent.
client = commands.Bot(command_prefix='.', intents=intents)
client.remove_command('help')

AUDIO_DIR = os.path.join(os.path.dirname(__file__), 'audio')

# Define Legacy Categories to preserve historical grouping
# Using list of tuples to maintain order of categories in display
LEGACY_CATEGORIES = [
    ('Other AOE sounds', {'301', '302', 'agu', 'bling', 'brain', 'brush', 'crap', 'dog', 'door', 'eh', 'eh2', 'fine', 'gg', 'hey', 'hey2', 'holo', 'lilai', 'ma', 'order', 'perv', 'pogo', 'thx'}),
    ('Additional taunts', {'2ja', '41', '69', 'ah', 'ah2', 'ahnia', 'baan', 'bb', 'bb2', 'black', 'call', 'da', 'dc', 'deserve', 'dick', 'dick2', 'dick3', 'die', 'die2', 'dio', 'dunno', 'fine2', 'fine3', 'g', 'gan', 'gan2', 'gan3', 'gibai', 'go', 'go2', 'guan', 'hehe', 'imp', 'in', 'hard', 'iyo', 'ja', 'jizz', 'jizz2', 'justice', 'lager', 'luv', 'maja', 'majaja', 'me', 'myaoe', 'nene', 'nice', 'no', 'no2', 'nodick', 'oyo', 'quack', 'reward', 'roger', 'say', 'spag', 'turk', 'up', 'wait', 'wifi', 'wp', 'yahoo', 'yay', 'yay2', 'where', 'zawarudo'}),
    ('May 2025', {'afk', 'ate', 'fish', 'ja', 'jizz3', 'kaka', 'micro', 'red', 'start'}),
    ('Aug 2025', {'air', 'barracks', 'boring', 'boring2', 'boring3', 'fire', 'nowood'}),
    ('Sep 2025', {'zz', 'zzz'}),
    ('Oct 2025', {'jan', 'respect', 'sit', 'forgot'}),
    ('Nov 2025', {'100'})
]

# Flatten legacy categories for easy lookup
LEGACY_LOOKUP = {}
for cat_name, items in LEGACY_CATEGORIES:
    for item in items:
        LEGACY_LOOKUP[item] = cat_name

# Voice Groups (Generated by Supervised Analysis)
# Format: 'group_id': [list of taunt names]
TAUNT_VOICE_GROUPS = {
    'group_1': ['afk', 'ate', 'dunno', 'fish', 'me', 'myaoe', 'no2', 'spag', 'start', 'wait', 'yay', 'da', 'dick', 'oyo', 'baan', 'exc', 'ja', 'justice', 'lose', 'nboring', 'no', 'nodick', 'red', 'side', 'where', 'hehe'],
    'group_2': ['2ja', 'black', 'dc', 'forgot', 'luv', 'respect', 'wp', 'ayo', 'song', 'zz', 'zzz'],
    'group_3': ['air', 'barracks', 'fire', 'in', 'nowood', 'da2', 'ah2'],
    'group_4': ['14', 'dick2', 'yay2', 'jan', 'jizz4', 'side', 'sula', 'hehe'],
    'group_5': ['hard', 'imp', 'lager', 'nohelp', 'dick3', 'hurry2', 'hehe'],
    'group_6': ['ah', 'ah3', 'bb', 'bb2', 'jizz', 'jizz2', 'kaka', 'quack'],
    'group_7': ['boring', 'boring2', 'boring3', 'g', 'horny', 'sit'],
    'group_8': ['climax', 'climax2'],
    'group_9': ['0friend', '1friend'],
    'unknown': ['call', 'die', 'die2', 'dio', 'go', 'go2', 'jizz3', 'maja', 'majaja', 'micro', 'nene', 'nice', 'roger', 'turk', 'up', 'wifi', 'yahoo', 'zawarudo', 'say', 'ahnia', 'deserve', 'fine2', 'fine3', 'gan2', 'gan3', 'gibai', 'guan']
}

# Map Users to Specific Taunts OR Voice Groups
USER_TAUNT_MAPPING = {
    'monkie35k': 'group_5',
    'kenneth0818': 'group_6',
    'ump98812': 'group_2',
    'laosongzuilan': 'group_1',
    'youryi1180': 'group_3',
    '113dgeh0g': 'group_4',
    '.kansu': 'group_7',
    'cityhunter1624': 'group_8',
    'yuuuu__uuuu___': 'group_9'
}

import random

@client.event
async def on_ready():
    await client.change_presence(status=discord.Status.idle, activity=discord.Activity(type=discord.ActivityType.listening, name='.help'))
    print('TauntBot onboard.')
    print(f'Registered {len(client.commands)} commands (excluding help).')

async def play_taunt_file(voice, tauntUrl, disconnect_delay=0, speed=1.0):
    if not voice:
        print("Voice client is None, cannot play.")
        return

    if os.path.exists(tauntUrl):
        # Using rubberband for high-quality time stretching without robotic artifacts
        options = f'-filter:a "rubberband=tempo={speed}"' if speed != 1.0 else None
        
        if options:
            source = FFmpegPCMAudio(tauntUrl, options=options)
        else:
            source = FFmpegPCMAudio(tauntUrl)

        if voice.is_playing():
            voice.stop()

        try:
            player = voice.play(source)
        except Exception as e:
            print(f"Error playing audio: {e}")
            return

        while voice.is_playing():
            await asyncio.sleep(1)
            
        # Optional: Wait before disconnecting
        if disconnect_delay > 0:
            await asyncio.sleep(disconnect_delay)
            
        # Check if something else started playing while we waited
        if voice.is_playing():
            print("Another sound started, cancelling disconnect.")
            return

        try:
            if voice.is_connected():
                await voice.disconnect()
                print('Bot peace out.')
        except:
            pass # Already disconnected or other error
    else:
        print(f'File not found: {tauntUrl}')

async def play_taunt(ctx, *args):
    botMessage = ''
    speed = 1.0
    for arg in args:
        try:
            val = abs(float(arg))
            if 0.5 <= val <= 100.0:
                speed = val
            elif val > 0 and val < 0.5:
                speed = 0.5
        except ValueError:
            pass

    if ctx.message.author.voice == None:
        # Fallback: Join the voice channel with the most members
        voice_channels = ctx.guild.voice_channels
        if voice_channels:
            # Sort by member count (descending)
            voice_channels.sort(key=lambda vc: len(vc.members), reverse=True)
            target_channel = voice_channels[0]
            
            # Send warning message
            botMessage = await ctx.send(f'{ctx.message.author.mention} You have to join voice channel to hear the taunt! I\'ll join {target_channel.name} since it has the most people.')
            
            channel = target_channel
        else:
            # No voice channels found
            botMessage = await ctx.send(f'{ctx.message.author.mention} You have to join voice channel to hear the taunt! And there are no voice channels for me to join.')
            await asyncio.sleep(5)
            # Cleanup command and bot message right before function return
            await botMessage.delete()
            await ctx.message.delete()
            return
    else:
        channel = ctx.message.author.voice.channel

    voice = get(client.voice_clients, guild=ctx.guild)
    if voice and voice.is_connected():
        await voice.move_to(channel)
    else:
        try:
            voice = await channel.connect()
        except:
            print('Bot already connected.')

    # Dynamic file path based on command name
    tauntCode = ctx.command.name
    tauntUrl = os.path.join(AUDIO_DIR, f'{tauntCode}.ogg')
    
    # Commands stay for 60 seconds
    await play_taunt_file(voice, tauntUrl, disconnect_delay=60, speed=speed)

    # Cleanup command (and bot message)
    if botMessage != '':
        await botMessage.delete()
    await ctx.message.delete()
    print('Cleared commands.')

@client.event
async def on_voice_state_update(member, before, after):
    # Ignore bots
    if member.bot:
        return

    # Trigger only on joining a channel (from None or from another channel)
    if after.channel is not None and before.channel != after.channel:
        channel = after.channel
        guild = member.guild
        
        voice = get(client.voice_clients, guild=guild)
        if voice and voice.is_connected():
             if voice.channel != channel:
                await voice.move_to(channel)
        else:
            try:
                voice = await channel.connect()
            except:
                print('Bot already connected.')
        
        if os.path.exists(AUDIO_DIR):
            files = [f for f in os.listdir(AUDIO_DIR) if f.endswith('.ogg')]
            if not files:
                return
                
            user_name = member.name
            
            selected_taunt = None
            
            # 1 & 2. Check if user is mapped in the unified USER_TAUNT_MAPPING
            if user_name in USER_TAUNT_MAPPING:
                mapped_value = USER_TAUNT_MAPPING[user_name]
                
                # Option A: Mapped to a Voice Group
                if mapped_value.startswith('group_') and mapped_value in TAUNT_VOICE_GROUPS:
                    # 50% chance to play from their specific group, 50% chance to play from ANY taunt
                    if random.random() < 0.50:
                        possible_taunts = TAUNT_VOICE_GROUPS[mapped_value]
                        valid_taunts = [t for t in possible_taunts if f"{t}.ogg" in files]
                        if valid_taunts:
                            selected_taunt = random.choice(valid_taunts)
                            print(f"[GROUP HIT] User {user_name} mapped to {mapped_value}. Selected {selected_taunt}")
                
                # Option B: Mapped to a specific single taunt
                else: 
                     target_filename = f"{mapped_value}.ogg"
                     if target_filename in files:
                         tauntUrl = os.path.join(AUDIO_DIR, target_filename)
                         print(f"User {user_name} joined {channel.name}, playing strictly assigned {target_filename}")
                         await play_taunt_file(voice, tauntUrl, disconnect_delay=0)
                         return
            
            # 3. Handle unmapped users OR 50% chance fallback for mapped users
            if selected_taunt is None:
                if user_name not in USER_TAUNT_MAPPING:
                    # Unlabeled member: 50% unknown pool, 50% labeled pools (Groups 1-9)
                    if random.random() < 0.50:
                        possible_taunts = TAUNT_VOICE_GROUPS.get('unknown', [])
                        valid_taunts = [t for t in possible_taunts if f"{t}.ogg" in files]
                        if valid_taunts:
                            selected_taunt = random.choice(valid_taunts)
                            print(f"[UNKNOWN POOL HIT] Unmapped user {user_name}. Selected {selected_taunt}")
                    else:
                        # Pool all known groups together
                        possible_taunts = []
                        for grp, taunts in TAUNT_VOICE_GROUPS.items():
                            if grp.startswith('group_'):
                                possible_taunts.extend(taunts)
                        valid_taunts = [t for t in possible_taunts if f"{t}.ogg" in files]
                        if valid_taunts:
                            selected_taunt = random.choice(valid_taunts)
                            print(f"[KNOWN POOL HIT] Unmapped user {user_name}. Selected {selected_taunt}")
                            
            # 4. Total Fail-safe Fallback (if pools are empty or 50% mapped fallback triggered)
            if selected_taunt is None:
                selected_taunt = random.choice(files)[:-4] # remove .ogg
                print(f"[RANDOM FALLBACK] User {user_name}. Selected {selected_taunt}")

            tauntUrl = os.path.join(AUDIO_DIR, f"{selected_taunt}.ogg")
            await play_taunt_file(voice, tauntUrl, disconnect_delay=0)

# Dynamic Command Registration
if os.path.exists(AUDIO_DIR):
    for filename in os.listdir(AUDIO_DIR):
        if filename.endswith('.ogg'):
            command_name = filename[:-4] # Remove .ogg extension
            # Create a new command object for each file, using the generic handler
            cmd = commands.Command(play_taunt, name=command_name)
            client.add_command(cmd)

@client.command(pass_context=True)
async def help(ctx):
    channel = ctx.message.channel
    embed = discord.Embed(color = discord.Color.orange())
    
    helpMsg = 'Simply type a dot ( . ) followed by one of the commands below. The bot will enter voice channel and shout out the taunt.\n Example: type " .14 " -> bot will say "Start the game already"\n\n**Playback Speed**\nYou can change the playback speed by adding a number after the command.\nExample: type ".nowood 0.5" to play at half speed, or ".nowood 2" for double speed.\n\n**Channel Selection**\nIf you are not in a voice channel, the bot will automatically join the most populated voice channel.'
    embed.add_field(name='Usage', value=helpMsg, inline=False)
    
    # Organize commands
    categorized_commands = defaultdict(list)
    date_based_categories = set()
    
    for command in client.commands:
        if command.name == 'help' or command.name == '0':
            continue
            
        cmd_name = command.name
        
        # Check Legacy
        if cmd_name in LEGACY_LOOKUP:
            cat = LEGACY_LOOKUP[cmd_name]
            categorized_commands[cat].append(cmd_name)
        else:
            # Determine Date Category
            try:
                filepath = os.path.join(AUDIO_DIR, f"{cmd_name}.ogg")
                if os.path.exists(filepath):
                    creation_time = os.path.getctime(filepath)
                    dt = datetime.fromtimestamp(creation_time)
                    
                    if dt.year < 2025:
                        categorized_commands["Standard Taunts"].append(cmd_name)
                    else:
                        cat_name = dt.strftime("%b %Y") # e.g. "Dec 2025"
                        categorized_commands[cat_name].append(cmd_name)
                        date_based_categories.add((creation_time, cat_name)) # Store tuples for sorting
                else:
                    categorized_commands["Uncategorized"].append(cmd_name)
            except Exception as e:
                print(f"Error categorizing {cmd_name}: {e}")
                categorized_commands["Uncategorized"].append(cmd_name)
    
    # Build Embed
    
    # 1. Standard Taunts (Pre-2025, non-legacy)
    if categorized_commands["Standard Taunts"]:
         cmds = sorted(categorized_commands["Standard Taunts"])
         embed.add_field(name="Standard Taunts", value=', '.join(cmds), inline=False)

    # 2. Legacy Categories (In Order)
    for cat_name, _ in LEGACY_CATEGORIES:
        if cat_name in categorized_commands and categorized_commands[cat_name]:
            cmds = sorted(categorized_commands[cat_name])
            embed.add_field(name=cat_name, value=', '.join(cmds), inline=False)

    # 3. Date Categories (Chronological)
    # Filter out categories that match legacy names if any overlap (unlikely with this logic, but good practice)
    processed_cats = {c[0] for c in LEGACY_CATEGORIES}
    
    # Sort by timestamp
    sorted_date_cats = sorted(list(date_based_categories), key=lambda x: x[0])
    
    for _, cat_name in sorted_date_cats:
        if cat_name not in processed_cats and categorized_commands[cat_name]:
            cmds = sorted(categorized_commands[cat_name])
            embed.add_field(name=cat_name, value=', '.join(cmds), inline=False)
            processed_cats.add(cat_name) # Mark processed
            
    # 3. Uncategorized (New stuff that failed date check?)
    if categorized_commands["Uncategorized"]:
         cmds = sorted(categorized_commands["Uncategorized"])
         embed.add_field(name="Uncategorized", value=', '.join(cmds), inline=False)

    await channel.send(embed=embed)

@client.command(name='0')
async def leave(ctx):
    server = ctx.message.guild.voice_client
    if server:
        await server.disconnect()

import socket
import sys

# Define a specific port for the bot's Instance Lock
SINGLE_INSTANCE_PORT = 12345
_instance_lock_socket = None

def acquire_single_instance_lock():
    global _instance_lock_socket
    _instance_lock_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        # If the port is already bound, another bot is running
        _instance_lock_socket.bind(("127.0.0.1", SINGLE_INSTANCE_PORT))
        print("Obtained single-instance lock. Starting bot...")
    except OSError:
        print(f"CRITICAL ERROR: Another instance of the bot is already running (Port {SINGLE_INSTANCE_PORT} is in use).")
        print("Exiting to prevent duplicate bot connections.")
        sys.exit(1)

if __name__ == "__main__":
    acquire_single_instance_lock()
    client.run(TOKEN)
