import os
import sys
import socket
import random
import logging
import discord, asyncio
from discord import app_commands
from dotenv import load_dotenv
from discord import FFmpegPCMAudio
from discord.ext import commands
from discord.utils import get
from datetime import datetime
from collections import defaultdict, deque
from typing import List

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
load_dotenv(os.path.join(ROOT_DIR, '.env'))
load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')

# Define specific Servers for instant Slash Command syncing
MY_GUILDS = [
    discord.Object(id=848324685628178462), # Garage
    discord.Object(id=717313306754547812)  # AOE2
]

intents = discord.Intents.all()
intents.members = True  # Subscribe to the privileged members intent.
# We keep prefix commands but will restrict their usage via a check
client = commands.Bot(command_prefix='.', intents=intents)
client.remove_command('help')

AUDIO_DIR = os.path.join(os.path.dirname(__file__), 'audio')
LOG_DIR = os.path.join(ROOT_DIR, 'logs')
LOG_FILE = os.path.join(LOG_DIR, 'tauntbot.log')
os.makedirs(LOG_DIR, exist_ok=True)

logger = logging.getLogger('tauntbot')
logger.setLevel(logging.INFO)
if not logger.handlers:
    formatter = logging.Formatter('%(asctime)s | %(levelname)s | %(message)s')
    stream_handler = logging.StreamHandler(sys.stdout)
    stream_handler.setFormatter(formatter)
    file_handler = logging.FileHandler(LOG_FILE, encoding='utf-8')
    file_handler.setFormatter(formatter)
    logger.addHandler(stream_handler)
    logger.addHandler(file_handler)

_guild_voice_locks = {}

# Define Legacy Categories to preserve historical grouping
# Using list of tuples to maintain order of categories in display
LEGACY_CATEGORIES = [
    ('Other AOE sounds', {'301', '302', 'agu', 'bling', 'brain', 'brush', 'crap', 'dog', 'door', 'eh', 'eh2', 'fine', 'gg', 'hey', 'hey2', 'holo', 'lilai', 'ma', 'order', 'perv', 'pogo', 'thx'}),
    ('Additional taunts', {'2ja', '41', '69', 'ah', 'ah2', 'ahnia', 'baan', 'bb', 'bb2', 'black', 'call', 'da', 'dc', 'deserve', 'dick', 'dick2', 'dick3', 'die', 'die2', 'dio', 'dunno', 'fine2', 'fine3', 'g', 'gan', 'gan2', 'gan3', 'gibai', 'go', 'go2', 'guan', 'hehe', 'imp', 'in', 'hard', 'iyo', 'ja', 'jizz', 'jizz2', 'justice', 'lager', 'luv', 'maja', 'majaja', 'me', 'myaoe', 'nene', 'nice', 'no', 'no2', 'nodick', 'oyo', 'quack', 'reward', 'roger', 'say', 'spag', 'turk', 'up', 'wait', 'wifi', 'wp', 'yahoo', 'yay', 'yay2', 'where', 'zawarudo'}),
    ('May 2025', {'afk', 'ate', 'fish', 'ja', 'jizz3', 'kaka', 'micro', 'red', 'start'}),
    ('Aug 2025', {'air', 'barracks', 'boring', 'boring2', 'boring3', 'fire', 'nowood'}),
    ('Sep 2025', {'zz', 'zzz'}),
    ('Oct 2025', {'jan', 'respect', 'sit', 'forgot'}),
    ('Nov 2025', {'100'})
]

# Flatten legacy categories for easy lookup
LEGACY_LOOKUP = {}
for cat_name, items in LEGACY_CATEGORIES:
    for item in items:
        LEGACY_LOOKUP[item] = cat_name

# Voice Groups (Generated by Supervised Analysis)
# Format: 'group_id': [list of taunt names]
TAUNT_VOICE_GROUPS = {
    'group_1': ['afk', 'ate', 'dunno', 'fish', 'me', 'myaoe', 'no2', 'spag', 'start', 'wait', 'yay', 'da', 'dick', 'oyo', 'baan', 'exc', 'ja', 'justice', 'lose', 'nboring', 'no', 'nodick', 'red', 'side', 'where', 'hehe'],
    'group_2': ['2ja', 'black', 'dc', 'forgot', 'luv', 'respect', 'wp', 'ayo', 'song', 'zz', 'zzz'],
    'group_3': ['air', 'barracks', 'fire', 'in', 'nowood', 'da2', 'ah2'],
    'group_4': ['14', 'dick2', 'yay2', 'jan', 'jizz4', 'side', 'sula', 'hehe'],
    'group_5': ['hard', 'imp', 'lager', 'nohelp', 'dick3', 'hurry2', 'hehe'],
    'group_6': ['ah', 'ah3', 'bb', 'bb2', 'jizz', 'jizz2', 'kaka', 'quack'],
    'group_7': ['boring', 'boring2', 'boring3', 'g', 'horny', 'sit'],
    'group_8': ['climax', 'climax2'],
    'group_9': ['0friend', '1friend'],
    'unknown': ['call', 'die', 'die2', 'dio', 'go', 'go2', 'jizz3', 'maja', 'majaja', 'micro', 'nene', 'nice', 'roger', 'turk', 'up', 'wifi', 'yahoo', 'zawarudo', 'say', 'ahnia', 'deserve', 'fine2', 'fine3', 'gan2', 'gan3', 'gibai', 'guan']
}

# Map Users to Specific Taunts OR Voice Groups
USER_TAUNT_MAPPING = {
    'monkie35k': 'group_5',
    'kenneth0818': 'group_6',
    'ump98812': 'group_2',
    'laosongzuilan': 'group_1',
    'youryi1180': 'group_3',
    '113dgeh0g': 'group_4',
    '.kansu': 'group_7',
    'cityhunter1624': 'group_8',
    'yuuuu__uuuu___': 'group_9'
}
USER_TAUNT_MAPPING = {k.lower(): v for k, v in USER_TAUNT_MAPPING.items()}

@client.event
async def on_ready():
    await client.change_presence(status=discord.Status.idle, activity=discord.Activity(type=discord.ActivityType.listening, name='.help or /t'))
    
    # Sync Slash Commands to specified Guilds instantly
    for guild_object in MY_GUILDS:
        try:
            client.tree.copy_global_to(guild=guild_object)
            await client.tree.sync(guild=guild_object)
            logger.info(f"Synced slash commands to guild {guild_object.id}")
        except Exception as e:
            logger.error(f"Failed to sync to guild {guild_object.id}: {e}")
            
    logger.info('TauntBot onboard.')
    logger.info(f'Registered {len(client.commands)} legacy prefix commands (excluding help).')

def get_guild_voice_lock(guild_id: int) -> asyncio.Lock:
    lock = _guild_voice_locks.get(guild_id)
    if lock is None:
        lock = asyncio.Lock()
        _guild_voice_locks[guild_id] = lock
    return lock

async def safe_delete_message(message):
    if message is None:
        return
    try:
        await message.delete()
    except (discord.Forbidden, discord.NotFound):
        pass
    except Exception as e:
        logger.warning(f'Failed to delete message: {e}')

async def ensure_voice_client(guild, channel):
    voice = get(client.voice_clients, guild=guild)

    if voice and voice.is_connected():
        if voice.channel != channel:
            try:
                await voice.move_to(channel)
            except Exception as e:
                logger.error(f'Failed to move voice client: {e}')
                return None
        return voice

    try:
        return await channel.connect()
    except discord.ClientException:
        # Handle races where another coroutine connected first.
        voice = get(client.voice_clients, guild=guild)
        if voice and voice.is_connected():
            if voice.channel != channel:
                try:
                    await voice.move_to(channel)
                except Exception as e:
                    logger.error(f'Failed to recover and move voice client: {e}')
                    return None
            return voice
        logger.error('Unable to recover existing voice client after connect race.')
        return None
    except Exception as e:
        logger.error(f'Failed to connect to voice channel: {e}')
        return None

def resolve_member_mapping(member, mapping):
    candidates = [getattr(member, 'name', None), getattr(member, 'display_name', None)]
    for candidate in candidates:
        if candidate:
            mapped_value = mapping.get(candidate.lower())
            if mapped_value:
                return candidate, mapped_value
    return None, None

def read_log_tail(lines: int) -> str:
    if not os.path.exists(LOG_FILE):
        return 'No log file exists yet.'
    try:
        with open(LOG_FILE, 'r', encoding='utf-8', errors='replace') as handle:
            tail_lines = deque(handle, maxlen=lines)
    except Exception as e:
        return f'Failed to read log file: {e}'

    if not tail_lines:
        return 'Log file is empty.'

    return ''.join(tail_lines).rstrip('\n')

def format_log_for_discord(text: str, max_chars: int = 1750) -> str:
    sanitized = text.replace('```', '`\u200b``')
    if len(sanitized) > max_chars:
        sanitized = f'...[truncated to last {max_chars} chars]\n{sanitized[-max_chars:]}'
    return sanitized

def voice_is_playing(voice) -> bool:
    try:
        return bool(voice.is_playing())
    except StopIteration:
        # Unit tests can mock finite side-effect sequences.
        return False
    except Exception as e:
        logger.warning(f'Failed to read voice playback state: {e}')
        return False

async def play_taunt_file(voice, tauntUrl, disconnect_delay=0, speed=1.0):
    if not voice:
        logger.warning('Voice client is None, cannot play.')
        return False

    if os.path.exists(tauntUrl):
        # Using adelay to prepend silence, fixing the 0.3s Discord warm-up skip.
        # Format: adelay=delay_ms|delay_ms (for stereo)
        silence_padding = "adelay=300|300"
        
        if speed != 1.0:
            # Chain rubberband for speed and adelay for padding
            options = f'-af "rubberband=tempo={speed},{silence_padding}"'
        else:
            options = f'-af "{silence_padding}"'
        
        source = FFmpegPCMAudio(tauntUrl, options=options)

        if voice_is_playing(voice):
            voice.stop()

        try:
            voice.play(source)
        except Exception as e:
            logger.error(f'Error playing audio "{tauntUrl}": {e}')
            return False

        # Give discord.py a brief moment to transition the player into "playing".
        await asyncio.sleep(0.15)
        
        async def wait_and_disconnect():
            try:
                playback_started = False
                while voice_is_playing(voice):
                    playback_started = True
                    await asyncio.sleep(0.1)

                if not playback_started:
                    logger.warning(f'Playback never reported "is_playing" for "{tauntUrl}".')
                    
                if disconnect_delay > 0:
                    await asyncio.sleep(disconnect_delay)
                    if not voice_is_playing(voice):
                        if voice.is_connected():
                            await voice.disconnect()
                            logger.info('Bot peace out.')
            except asyncio.CancelledError:
                # Task was cancelled by another play_taunt_file call
                pass
            except Exception as e:
                logger.error(f"Error in wait_and_disconnect task: {e}")

        # Cancel any existing wait_and_disconnect task to prevent premature disconnects
        if hasattr(voice, '_disconnect_task') and getattr(voice, '_disconnect_task') is not None:
            voice._disconnect_task.cancel()
            
        voice._disconnect_task = asyncio.create_task(wait_and_disconnect())
        return True
    else:
        logger.warning(f'File not found: {tauntUrl}')
        return False

async def play_taunt(ctx, *args):
    if ctx.guild is None:
        return

    lock = get_guild_voice_lock(ctx.guild.id)
    async with lock:
        botMessage = None
        speed = 1.0
        for arg in args:
            try:
                val = abs(float(arg))
                if 0.1 <= val <= 3.0:
                    speed = val
                elif val > 0 and val < 0.1:
                    speed = 0.1
            except ValueError:
                pass

        if ctx.message.author.voice is None:
            # Fallback: Join the voice channel with the most members
            voice_channels = ctx.guild.voice_channels
            if voice_channels:
                voice_channels.sort(key=lambda vc: len(vc.members), reverse=True)
                target_channel = voice_channels[0]
                botMessage = await ctx.send(
                    f"{ctx.message.author.mention} You have to join voice channel to hear the taunt! "
                    f"I'll join {target_channel.name} since it has the most people."
                )
                channel = target_channel
            else:
                botMessage = await ctx.send(
                    f"{ctx.message.author.mention} You have to join voice channel to hear the taunt! "
                    "And there are no voice channels for me to join."
                )
                await asyncio.sleep(5)
                await safe_delete_message(botMessage)
                await safe_delete_message(ctx.message)
                return
        else:
            channel = ctx.message.author.voice.channel

        voice = await ensure_voice_client(ctx.guild, channel)
        if voice is None:
            await safe_delete_message(botMessage)
            await safe_delete_message(ctx.message)
            return

        # Dynamic file path based on command name
        tauntCode = ctx.command.name
        tauntUrl = os.path.join(AUDIO_DIR, f'{tauntCode}.ogg')
        logger.info(
            f'Prefix request by {ctx.message.author} in guild {ctx.guild.id}: .{tauntCode} at {speed}x '
            f'-> {channel.name}'
        )
        
        # Commands stay for 60 seconds
        await play_taunt_file(voice, tauntUrl, disconnect_delay=60, speed=speed)

        await safe_delete_message(botMessage)
        await safe_delete_message(ctx.message)
        logger.info(f'Played prefix command .{tauntCode} and attempted cleanup.')

# --- Slash Command Implementation --- #

async def taunt_autocomplete(
    interaction: discord.Interaction,
    current: str,
) -> List[app_commands.Choice[str]]:
    files = [f[:-4] for f in os.listdir(AUDIO_DIR) if f.endswith('.ogg')]
    
    # Split the current input to isolate the taunt name from the speed
    parts = current.split(" ", 1)
    search_term = parts[0]
    
    # If there is a space and stuff after it, save it to append to the choices
    speed_suffix = ""
    if len(parts) > 1:
        speed_suffix = " " + parts[1]
    elif current.endswith(" "):
        speed_suffix = " "

    # Find matching taunt names based on the first word
    matches = [f for f in files if search_term.lower() in f.lower()]
    
    # Discord limits autocomplete to 25 choices. 
    # Return the full matched string: "[TauntName] [Speed]"
    return [
        app_commands.Choice(name=f"{match}{speed_suffix}", value=f"{match}{speed_suffix}")
        for match in matches[:25]
    ]

@client.tree.command(name="t", description="Play a specific audio taunt")
@app_commands.describe(
    query="The taunt name, optionally followed by a speed number (0.1 to 3.0, e.g. 'yahoo 0.5')"
)
@app_commands.autocomplete(query=taunt_autocomplete)
async def slash_taunt(interaction: discord.Interaction, query: str):
    if interaction.guild is None:
        await interaction.response.send_message('This command only works in a server.', ephemeral=True)
        return

    # Defer immediately to prevent interaction timeout
    await interaction.response.defer(ephemeral=True)
    
    parts = query.strip().split()
    if not parts:
        await interaction.delete_original_response()
        return
        
    name = parts[0]
    speed_str = parts[1] if len(parts) > 1 else "1.0"
    
    # Parse the user-input string gracefully (to handle ".5" instead of "0.5")
    parsed_speed = 1.0
    try:
        val = abs(float(speed_str))
        if 0.1 <= val <= 3.0:
            parsed_speed = val
        elif val > 0 and val < 0.1:
            parsed_speed = 0.1
    except ValueError:
        pass # Fallback to 1.0 if they type gibberish or nothing
        
    filename = f"{name}.ogg"
    tauntUrl = os.path.join(AUDIO_DIR, filename)
    
    if not os.path.exists(tauntUrl):
        await interaction.delete_original_response()
        return

    lock = get_guild_voice_lock(interaction.guild.id)
    async with lock:
        # Check Voice Channel status
        if interaction.user.voice is None:
            voice_channels = interaction.guild.voice_channels
            if voice_channels:
                voice_channels.sort(key=lambda vc: len(vc.members), reverse=True)
                channel = voice_channels[0]
            else:
                await interaction.delete_original_response()
                return
        else:
            channel = interaction.user.voice.channel

        voice = await ensure_voice_client(interaction.guild, channel)
        if voice is None:
            await interaction.delete_original_response()
            return

        # Play the Audio
        await interaction.delete_original_response()
        logger.info(
            f'Slash request by {interaction.user} in guild {interaction.guild.id}: /t {name} {parsed_speed} '
            f'-> {channel.name}'
        )
        await play_taunt_file(voice, tauntUrl, disconnect_delay=60, speed=parsed_speed)
        logger.info(f'Played slash command /t {name} at {parsed_speed}x speed.')

@client.tree.command(name="logs", description="Show recent taunt bot logs")
@app_commands.describe(lines="How many lines to show from the end of the log file (1-100)")
async def slash_logs(interaction: discord.Interaction, lines: app_commands.Range[int, 1, 100] = 20):
    log_excerpt = read_log_tail(lines)
    content = format_log_for_discord(log_excerpt)
    await interaction.response.send_message(f"```text\n{content}\n```", ephemeral=True)

# --- Global Restriction for Legacy Prefix Commands --- #

ALLOWED_LEGACY_CHANNELS = {'command', 'click here to speak', 'team-1', 'team-2', 'café', 'cafe'}

@client.check
async def globally_restrict_prefix_commands(ctx):
    # Ensure '.' text commands ONLY work in explicitly allowed channels
    if getattr(ctx.channel, 'name', '').lower() in ALLOWED_LEGACY_CHANNELS:
        return True
    
    # If the user typed a '.' command anywhere else, ignore it silently.
    # Note: returning False naturally raises discord.ext.commands.errors.CheckFailure
    return False

@client.event
async def on_command_error(ctx, error):
    # Ignore the error caused by typing a '.' command in the wrong channel to keep console clean
    if isinstance(error, commands.CheckFailure):
        pass
    elif isinstance(error, commands.CommandNotFound):
        pass
    else:
        logger.error(f"Ignoring exception in command {ctx.command}: {error}")

@client.event
async def on_voice_state_update(member, before, after):
    # Ignore bots
    if member.bot:
        return

    # Trigger only on joining a channel (from None or from another channel)
    if after.channel is not None and before.channel != after.channel:
        if member.guild is None:
            return

        lock = get_guild_voice_lock(member.guild.id)
        async with lock:
            channel = after.channel
            guild = member.guild
            
            active_voice = get(client.voice_clients, guild=guild)
            if active_voice and active_voice.is_connected() and voice_is_playing(active_voice):
                logger.info(
                    f'Skipping auto-taunt for {member.name} in {channel.name}; '
                    'bot is already playing audio.'
                )
                return

            voice = await ensure_voice_client(guild, channel)
            if voice is None:
                return
            
            if os.path.exists(AUDIO_DIR):
                files = [f for f in os.listdir(AUDIO_DIR) if f.endswith('.ogg')]
                if not files:
                    return
                    
                selected_taunt = None
                
                # 1 & 2. Check if user is mapped in the unified USER_TAUNT_MAPPING
                mapped_name, mapped_value = resolve_member_mapping(member, USER_TAUNT_MAPPING)
                if mapped_value:
                    # Option A: Mapped to a Voice Group
                    if mapped_value.startswith('group_') and mapped_value in TAUNT_VOICE_GROUPS:
                        # 50% chance to play from their specific group, 50% chance to play from ANY taunt
                        if random.random() < 0.50:
                            possible_taunts = TAUNT_VOICE_GROUPS[mapped_value]
                            valid_taunts = [t for t in possible_taunts if f"{t}.ogg" in files]
                            if valid_taunts:
                                selected_taunt = random.choice(valid_taunts)
                                logger.info(
                                    f"[GROUP HIT] User {mapped_name} mapped to {mapped_value}. "
                                    f"Selected {selected_taunt}"
                                )
                    
                    # Option B: Mapped to a specific single taunt
                    else: 
                        target_filename = f"{mapped_value}.ogg"
                        if target_filename in files:
                            tauntUrl = os.path.join(AUDIO_DIR, target_filename)
                            logger.info(
                                f"User {mapped_name} joined {channel.name}, "
                                f"playing strictly assigned {target_filename}"
                            )
                            await play_taunt_file(voice, tauntUrl, disconnect_delay=0)
                            return
                
                # 3. Handle unmapped users OR 50% chance fallback for mapped users
                if selected_taunt is None:
                    if mapped_value is None:
                        # Unlabeled member: 50% unknown pool, 50% labeled pools (Groups 1-9)
                        if random.random() < 0.50:
                            possible_taunts = TAUNT_VOICE_GROUPS.get('unknown', [])
                            valid_taunts = [t for t in possible_taunts if f"{t}.ogg" in files]
                            if valid_taunts:
                                selected_taunt = random.choice(valid_taunts)
                                logger.info(
                                    f"[UNKNOWN POOL HIT] Unmapped user {member.name}. Selected {selected_taunt}"
                                )
                        else:
                            # Pool all known groups together
                            possible_taunts = []
                            for grp, taunts in TAUNT_VOICE_GROUPS.items():
                                if grp.startswith('group_'):
                                    possible_taunts.extend(taunts)
                            valid_taunts = [t for t in possible_taunts if f"{t}.ogg" in files]
                            if valid_taunts:
                                selected_taunt = random.choice(valid_taunts)
                                logger.info(
                                    f"[KNOWN POOL HIT] Unmapped user {member.name}. Selected {selected_taunt}"
                                )
                                
                # 4. Total Fail-safe Fallback (if pools are empty or 50% mapped fallback triggered)
                if selected_taunt is None:
                    selected_taunt = random.choice(files)[:-4] # remove .ogg
                    logger.info(f"[RANDOM FALLBACK] User {member.name}. Selected {selected_taunt}")

                tauntUrl = os.path.join(AUDIO_DIR, f"{selected_taunt}.ogg")
                await play_taunt_file(voice, tauntUrl, disconnect_delay=0)

# Dynamic Command Registration
if os.path.exists(AUDIO_DIR):
    for filename in os.listdir(AUDIO_DIR):
        if filename.endswith('.ogg'):
            command_name = filename[:-4] # Remove .ogg extension
            # Create a new command object for each file, using the generic handler
            cmd = commands.Command(play_taunt, name=command_name)
            client.add_command(cmd)

def get_help_embed():
    embed = discord.Embed(color = discord.Color.orange())
    
    helpMsg = 'Simply type a dot ( . ) followed by one of the commands below. The bot will enter voice channel and shout out the taunt.\n Example: type " .14 " -> bot will say "Start the game already"\n\n**Playback Speed**\nYou can change the playback speed by adding a number after the command.\nExample: type ".nowood 0.5" to play at half speed, or ".nowood 2" for double speed.\n\n**Channel Selection**\nIf you are not in a voice channel, the bot will automatically join the most populated voice channel.'
    embed.add_field(name='Usage', value=helpMsg, inline=False)
    
    # Organize commands
    categorized_commands = defaultdict(list)
    date_based_categories = set()
    
    for command in client.commands:
        if command.name == 'help' or command.name == '0':
            continue
            
        cmd_name = command.name
        
        # Check Legacy
        if cmd_name in LEGACY_LOOKUP:
            cat = LEGACY_LOOKUP[cmd_name]
            categorized_commands[cat].append(cmd_name)
        else:
            # Determine Date Category
            try:
                filepath = os.path.join(AUDIO_DIR, f"{cmd_name}.ogg")
                if os.path.exists(filepath):
                    creation_time = os.path.getctime(filepath)
                    dt = datetime.fromtimestamp(creation_time)
                    
                    if dt.year < 2025:
                        categorized_commands["Standard Taunts"].append(cmd_name)
                    else:
                        cat_name = dt.strftime("%b %Y") # e.g. "Dec 2025"
                        categorized_commands[cat_name].append(cmd_name)
                        date_based_categories.add((creation_time, cat_name)) # Store tuples for sorting
                else:
                    categorized_commands["Uncategorized"].append(cmd_name)
            except Exception as e:
                logger.warning(f"Error categorizing {cmd_name}: {e}")
                categorized_commands["Uncategorized"].append(cmd_name)
    
    # Build Embed
    
    # 1. Standard Taunts (Pre-2025, non-legacy)
    if categorized_commands["Standard Taunts"]:
         cmds = sorted(categorized_commands["Standard Taunts"])
         embed.add_field(name="Standard Taunts", value=', '.join(cmds), inline=False)

    # 2. Legacy Categories (In Order)
    for cat_name, _ in LEGACY_CATEGORIES:
        if cat_name in categorized_commands and categorized_commands[cat_name]:
            cmds = sorted(categorized_commands[cat_name])
            embed.add_field(name=cat_name, value=', '.join(cmds), inline=False)

    # 3. Date Categories (Chronological)
    # Filter out categories that match legacy names if any overlap (unlikely with this logic, but good practice)
    processed_cats = {c[0] for c in LEGACY_CATEGORIES}
    
    # Sort by timestamp
    sorted_date_cats = sorted(list(date_based_categories), key=lambda x: x[0])
    
    for _, cat_name in sorted_date_cats:
        if cat_name not in processed_cats and categorized_commands[cat_name]:
            cmds = sorted(categorized_commands[cat_name])
            embed.add_field(name=cat_name, value=', '.join(cmds), inline=False)
            processed_cats.add(cat_name) # Mark processed
            
    # 4. Uncategorized (New stuff that failed date check?)
    if categorized_commands["Uncategorized"]:
         cmds = sorted(categorized_commands["Uncategorized"])
         embed.add_field(name="Uncategorized", value=', '.join(cmds), inline=False)
         
    return embed

@client.command(pass_context=True)
async def help(ctx):
    await ctx.message.channel.send(embed=get_help_embed())

@client.tree.command(name="help", description="Show the list of available taunts")
async def slash_help(interaction: discord.Interaction):
    # Ephemeral = True means only the command runner can see the giant help menu
    await interaction.response.send_message(embed=get_help_embed(), ephemeral=True)

@client.command(name='0')
async def leave(ctx):
    server = ctx.message.guild.voice_client
    if server:
        await server.disconnect()

# Define a specific port for the bot's Instance Lock
SINGLE_INSTANCE_PORT = 12345
_instance_lock_socket = None

def acquire_single_instance_lock():
    global _instance_lock_socket
    _instance_lock_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        # If the port is already bound, another bot is running
        _instance_lock_socket.bind(("127.0.0.1", SINGLE_INSTANCE_PORT))
        logger.info("Obtained single-instance lock. Starting bot...")
    except OSError:
        logger.critical(
            f"Another instance of the bot is already running (Port {SINGLE_INSTANCE_PORT} is in use)."
        )
        logger.critical("Exiting to prevent duplicate bot connections.")
        sys.exit(1)

if __name__ == "__main__":
    acquire_single_instance_lock()
    client.run(TOKEN)
